name: Azure publish

on: [workflow_dispatch]

jobs:
  publish:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "3.1.412"

      - name: "Run dotnet build"
        working-directory: src
        run: dotnet build --configuration Release --output ./output

      - name: "Run Azure Functions Action"
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: ahk-github-monitor
          package: "./src/output"
          publish-profile: ${{ secrets.AZFUNCTION_PUBLISHPROFILE }}
